name: sprawozdanie

on: push

jobs:
  pdf:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Python + WeasyPrint (FAST PDF)
        run: |
          sudo apt-get update
          sudo apt-get install -y weasyprint
          pip install nbconvert ipykernel pint open-atmos-jupyter-utils scipy numpy matplotlib PyMPDATA

      - name: Execute notebook → HTML
        run: |
          jupyter nbconvert --execute \
            --to html \
            --output "report.html" \
            project/beach_slope.ipynb

      - name: Convert HTML → PDF (VERY FAST)
        run: |
          weasyprint report.html sprawozdanie.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: sprawozdanie
          path: sprawozdanie.pdf
